travis:
  secure:
    BINSTAR_TOKEN: Dk9Y3IGV+NMAB2S0nvX/aE3XzbOIM29RLeRfLyY/MJu7j7xgX5ddEViyR8tNPcMa9NxJ5v+mY+/QI59psk3CCSpxORNPJQUA1v9zVYhK2sZfdPLj4bpFlpcKnjBq1PWwnDW+DnMLtAhu/Zb6u1Mkq3ewvXeohphvmqDrHPvbQf2B49LDThv8vWxyEnVPC5E+QYgFVInknCc+bSs8XKP6ZxbWT7jkM87mEN7J399Qah5/OA3cKtATE8/lcxouWWWHoUzrXPZYbySGFwymYJZvW/OuNOgo/vmqwr8Qf7HOFmHoNwShxqd3zLbHLm7inQnqPqfkrV75+mO11XcmyLBeu1iN1/zavlHi7pVAY8z1L60lJdUAprkpaRUJI0+ogXiNlsK3W3FpXlZX9K92zz+TKw0HFeEddC3FP7UQWNQ/bxVisqdUqFWC21l6wciYaENV7HRpd8jA1OeRdXZDzdCknrucmXh6R0TQ8IVZ/Goq51yuOWPqrxKCCAIqJgTh3rS6Ifo2vThWHHVhRCtWG/Gs3Us+oJt3SeYcgTFDadCSWZgmusPymPoAD/qoRDy7Q8nOVQ4JlVL3rcokG6ux2OUoH+ttoZXQQ4dBuisfJ0sOKsw9c87v+QLDnzYPCltU4hAAdOSNBvjyyKkRfWvqp3jCSh+eWfWtyWc2bmfnrvZ3ifQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
